### ISSUE TITLE
Bug Report: A problem of article toc in an abnormal window size

### ISSUE THREAD

**Issue by furtherun** [WRXinYue/valaxy-theme-sakura#3]
Taking this deployed [page](https://sakura.wrxinyue.org/posts/long-toc#checkbox9) as an example, 

- open the web page and 
- resize the browser window to 1341px $\times$ 270 px (maybe just the width is large but the height is small can reproduct this bug)
- scroll to the page bottom

Now, I cannot scroll the page, because it always scrolls to the bottom automatically!

I try this process in the deployed page and the demo of release v0.5.5, both of them have this problem.
And I also try it in valaxy [page](https://yun.valaxy.site/posts/long-toc#checkbox9), but no this problem.

However, in a normal case, nobody reads articles on a very wide and flat page, so it may not be a bug.

**Comment by WRXinYue** [comment]
Thank you for submitting this issue!

We have successfully reproduced the situation you described: when the browser window is resized to a width of 1341px and a height of 270px, refreshing the page and scrolling to the bottom will cause the page to automatically scroll to the bottom, making it impossible to normally scroll and view the content. When the scroll wheel speed is fast, it might be possible to scroll back to the top successfully.

Although users rarely read articles in such a wide and flat window during actual use, this issue still needs to be resolved to ensure a good user experience in all situations.

We will investigate this issue as soon as possible and fix it in the next version. Thank you again for your feedback!

**Comment by WRXinYue** [comment]
Specifically, when [Outline](https://github.com/WRXinYue/valaxy-theme-sakura/blob/main/theme/components/SakuraOutline.vue) reaches the bottom of the view, as in this [example](https://sakura.wrxinyue.org/posts/long-toc#checkbox9), it triggers `scrollIntoView()`. Since this is controlling the element within the view, the last tag will cause the toc component to reset to the top when `scrollIntoView()` is triggered. Therefore, this operation is repeatedly executed during the scrolling process. In the case of the [Yun Theme](https://yun.valaxy.site/posts/long-toc#checkbox9) example, this issue does not occur because the toc component always remains at the bottom of the view. The current solution is to disable this view scrolling trigger. For reference, as seen in the source code of the [Nuxt UI documentation](https://ui.nuxt.com/getting-started/installation#edge) website, the toc element does not trigger `scrollIntoView()` when it is out of view.
